20221026_1_accounts_1/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
]

20221026_1_accounts_1/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:article_pk>/delete', views.delete, name='delete'),
    path('<int:article_pk>/detail', views.detail, name='detail'),
    path('<int:article_pk>/update', views.update, name='update'),
]

20221026_1_accounts_1/pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

20221026_1_accounts_1/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

20221026_1_accounts_1/articles/models.py
from django.db import models

# Create your models here.

class Articles(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

20221026_1_accounts_1/articles/forms.py
from django import forms
from .models import Articles


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ['title', 'content']

20221026_1_accounts_1/accounts/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('articles:index')
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)

20221026_1_accounts_1/articles/views.py
from django.shortcuts import render, redirect
from .models import Articles
from .forms import ArticleForm
# Create your views here.

def index(request):
    articles = Articles.objects.order_by('-pk')
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def new(request):
    if request.method == 'POST':
        article_form  = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:index')
    else:
        article_form = ArticleForm()
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)

def delete(request, article_pk):
    article = Articles.objects.get(pk=article_pk)
    article.delete()
    return redirect('articles:index')

def detail(request, article_pk):
    article = Articles.objects.get(pk = article_pk)
    context = {
        'article': article
    }
    return render(request, 'articles/detail.html', context)

def update(request, article_pk):
    article = Articles.objects.get(pk=article_pk)
    if request.method == 'POST':
        article_form  = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:index')
    else:
        article_form = ArticleForm(instance=article)
    context = {
        'article_form': article_form
    }
    return render(request, 'articles/form.html', context)

20221026_1_accounts_1/articles/templates/articles/create.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block body %}

<form action="{% url 'articles:new' %}" method="POST">
    {% csrf_token %}

    {% for field in article_form %}
    <p>
        {{ field }}
    </p>
        {{ field.label_tag }}
    {% endfor %}

    {% bootstrap_form article_form %}
    {% bootstrap_button button_type='submit' content='OK' %}
</form>

<a href="{% url 'articles:index' %}">메인</a>
{% endblock %}

20221026_1_accounts_1/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block body %}
<h2>{{ article.pk}}번</h2>
<p>{{ article.created_at|date:"SHORT_DATETIME_FORMAT" }} | {{ article.updated_at|date:"y-m-d D" }}</p>
<p>{{ article.content }}</p>
<a href="{% url 'articles:update' article.pk %}">글 수정</a>
{% endblock %}

20221026_1_accounts_1/articles/templates/articles/form.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

<p>{{ request.path }}</p>
<p>{{ request.method }}</p>
<p>{{ request.GET }}</p>

<p>{{ request.resolver_match.url_name }}</p>
{% if request.resolver_match.url_name == 'new' %}
<h1>글 생성</h1>
{% else %}
<h1>글 수정</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form article_form %}
    {% bootstrap_button button_type='submit' content='OK' %}
</form>
{% endblock %}

20221026_1_accounts_1/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block body %}
{% load static %}
<h1>메인 페이지</h1>

<p><img src="{% static 'images/image1.jpg' %}" alt="image1"></p>

<a href="{% url 'articles:new' %}">글 작성</a>
{% for article in articles %}
<p><a href="{% url 'articles:detail' article.pk %}">{{ article.pk }}</a></p>
<p>{{ article.title }}</p>
<p>{{ article.content }}</p>
<p>{{ article.created_at }} | {{ article.updated_at }}</p>
<a href="{% url 'articles:delete' article.pk %}">글 삭제</a>
{% endfor %}
{% endblock %}